-- MySQL Script generated by MySQL Workbench
-- Mon Sep  8 23:31:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clowear
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clowear
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clowear` DEFAULT CHARACTER SET utf8 ;
USE `clowear` ;

-- -----------------------------------------------------
-- Table `clowear`.`fabrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clowear`.`fabrics` (
  `fabricId` INT NOT NULL AUTO_INCREMENT,
  `fabricType` VARCHAR(45) NOT NULL,
  `fabricColor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fabricId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clowear`.`production`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clowear`.`production` (
  `productId` INT NOT NULL AUTO_INCREMENT,
  `productType` VARCHAR(45) NOT NULL,
  `productSize` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`productId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clowear`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clowear`.`orders` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `productId` INT NOT NULL,
  `fabricId` INT NOT NULL,
  `orderCost` INT NOT NULL,
  `orderDate` DATE NOT NULL,
  PRIMARY KEY (`orderId`),
  INDEX `productId_idx` (`productId` ASC) VISIBLE,
  INDEX `fabricId_idx` (`fabricId` ASC) VISIBLE,
  CONSTRAINT `productId`
    FOREIGN KEY (`productId`)
    REFERENCES `clowear`.`production` (`productId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fabricId`
    FOREIGN KEY (`fabricId`)
    REFERENCES `clowear`.`fabrics` (`fabricId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
